// filepath: c:\Users\Sagar Guney\OneDrive\Documents\Cprograms\DPDZeroAssignment\prometheus\prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'service_1'
    static_configs:
      - targets: ['service_1:8001']

  - job_name: 'service_2'
    static_configs:
      - targets: ['service_2:8002']